package com.example.contratame.modelo;

public enum TiposServicios {
    INSTALACIONES, CONSTRUCCIÓN, AIRE_ACONDICIONADO, CARPINTERIA, PINTURA, PLOMERIA,
    ELECTRICIDAD, LIMPIEZA, JARDINERIA, COSTURERIA, GASISTA, CERRAJERIA, TRANSPORTE,
    BELLEZA, SEGURDAD
}
